on:
  # Triggered daily or manually
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  prd-mainnet-matches-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl "https://nexus.prd.oasis.io/v1/spec/v1.yaml" --fail -o v1.yaml
      - run: "sed -i 's/enum: \\[emerald, sapphire.*/[REMOVED]/g' ./v1.yaml"
      - run: git add .
      - run: curl "https://testnet.nexus.prd.oasis.io/v1/spec/v1.yaml" --fail -o v1.yaml
      - run: "sed -i 's/enum: \\[emerald, sapphire.*/[REMOVED]/g' ./v1.yaml"
      - name: Fail if anything changed
        run: "git diff --exit-code"
  stg-mainnet-matches-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl "https://nexus.stg.oasis.io/v1/spec/v1.yaml" --fail -o v1.yaml
      - run: "sed -i 's/enum: \\[emerald, sapphire.*/[REMOVED]/g' ./v1.yaml"
      - run: git add .
      - run: curl "https://testnet.nexus.stg.oasis.io/v1/spec/v1.yaml" --fail -o v1.yaml
      - run: "sed -i 's/enum: \\[emerald, sapphire.*/[REMOVED]/g' ./v1.yaml"
      - name: Fail if anything changed
        run: "git diff --exit-code"
